import json
import os
import subprocess
from dataclasses import dataclass
from typing import Tuple, Dict

# Import your custom tools
from tools.func_diff import get_func_diff, format_diff_for_agent
from tools.sandbox import pip_install

# ---------------------------------------------------------
# 1. Action & Observation Spaces
# ---------------------------------------------------------
@dataclass
class MigrationAction:
    file_path: str
    new_code: str

@dataclass
class MigrationObservation:
    status: str
    message: str
    context: str

# ---------------------------------------------------------
# 2. The OpenEnv Environment
# ---------------------------------------------------------
class MigrationEnv:
    def __init__(self):
        self.migration_targets = []
        self.current_task = None
        self.done = False
        self.current_step = 0
        self.max_steps = 5  # Max retries per file

    @property
    def state(self) -> dict:
        return {
            "current_task": self.current_task,
            "current_step": self.current_step,
            "is_done": self.done
        }

    def reset(self) -> MigrationObservation:
        """Loads a new migration task from the JSON list."""
        self.current_step = 0
        self.done = False

        # 1. Load the sorted target list generated by grapher.py
        if not self.migration_targets:
            try:
                # Adjust path to wherever your teammate's JSON lands
                with open("grapher/migration_plan.json", "r") as f:
                    self.migration_targets = json.load(f)
            except FileNotFoundError:
                return MigrationObservation("error", "Waiting for migration_plan.json", "")
        
        if not self.migration_targets:
            self.done = True
            return MigrationObservation("done", "All migrations complete!", "")
            
        self.current_task = self.migration_targets.pop(0)

        # 2. Dynamically parse the target library and function from the JSON
        # e.g., Extract "requests" and "get" from ["requests.get"]
        lib_used = self.current_task["library_functions_used"][0]
        old_lib, old_func = lib_used.split(".", 1)
        
        # Hardcoding the target library for now (requests -> httpx)
        new_lib = "httpx" 
        
        # 3. Use your func_diff tool to get the real-time API specifications
        diff_data = get_func_diff(old_lib, new_lib, old_func)
        api_specs = format_diff_for_agent(diff_data)

        # 4. Read the Python file that needs to be refactored
        file_to_edit = self.current_task["file_name"]

        # Files live under grapher/test_folder/, and file_name is
        # relative to that directory (e.g. "test2\\test.py").
        target_path = os.path.join("grapher", "test_folder", file_to_edit)

        try:
            with open(target_path, 'r') as f:
                old_code = f.read()
        except FileNotFoundError:
            old_code = f"# ERROR: Could not read {file_to_edit}"

        prompt_context = f"--- TARGET FILE ---\n{old_code}\n\n--- API SPECS ---\n{api_specs}"

        return MigrationObservation(
            status="start",
            message=f"Migrate '{self.current_task['function_name']}' from {old_lib} to {new_lib} in {file_to_edit}.",
            context=prompt_context
        )

    def step(self, action: MigrationAction) -> Tuple[MigrationObservation, float, bool, Dict]:
        """Writes the code, runs the tests, and returns the reward."""
        self.current_step += 1

        # 1. Agent edits the file (under grapher/test_folder)
        target_path = os.path.join("grapher", "test_folder", action.file_path)

        try:
            with open(target_path, 'w') as f:
                f.write(action.new_code)
        except Exception as e:
            return MigrationObservation("error", "Failed to write file.", str(e)), -1.0, False, {}

        # 2. The Grader (Pytest)
        grader_result = subprocess.run(
            ["pytest", target_path], 
            capture_output=True, 
            text=True
        )

        # 3. Reward Calculation
        if grader_result.returncode == 0:
            self.done = True
            return MigrationObservation("success", "Tests passed.", "Great job."), 100.0, True, {"step": self.current_step}
        else:
            reward = -1.0
            if self.current_step >= self.max_steps:
                self.done = True
                obs = MigrationObservation("failed", "Max attempts reached.", grader_result.stderr)
            else:
                self.done = False
                obs = MigrationObservation("error", "Tests failed. Fix the errors.", grader_result.stderr)
            
            return obs, reward, self.done, {"step": self.current_step}  